spring:
  application:
    name: sp-salary-calculator
  profiles:
    # 默认使用 dev 配置文件
    active: dev

  main:
    # 全局懒加载 SpringBoot 2.2 新增
    lazy-initialization: true

  jms:
    listener:
      # 我们不用jms
      auto-startup: false
  jmx:
    # 我们不用jmx
    enabled: false

  freemarker:
    suffix: .html
    request-context-attribute: request

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai


  aop:
    #开启CGLib代理
    proxy-target-class: true
    #自动代理
    auto: true

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  session:
    store-type: none
    redis:
      flushMode: immediate

# 在上下文中没有Executor bean的情况下，Spring Boot会自动配置ThreadPoolTaskExecutor，并使用合理的默认值，这些默认值可以自动关联到异步任务执行(@EnableAsync)和Spring MVC异步请求处理。
#如果您已经在上下文中定义了一个自定义执行器，那么常规任务执行(即@EnableAsync)将透明地使用它，但是Spring MVC支持将不会被配置，因为它需要一个AsyncTaskExecutor实现(名为applicationTaskExecutor)。根据您的目标安排，您可以将执行程序更改为ThreadPoolTaskExecutor，或者定义一个ThreadPoolTaskExecutor和一个包装自定义执行程序的AsyncConfigurer。
  task:
    execution:
      pool:
        core-size: 10
        max-size: 100
        queue-capacity: 50

  swagger:
    enabled: true
    email: blankhang@gmail.com
    name: blankhang
    url: https://blankhang.com
    baseUrl:
    description: springboot-distributed-transaction
    termsOfServiceUrl: https://blankhang.com
    title: springboot-distributed-transaction API documents
    version: 1.0
springfox:
  documentation:
    enabled: true
    swagger:
      v2:
        use-model-v3: true


management:
  endpoint:
    health:
      # 启用监控
      enabled: true
      show-components: always
      show-details: always

server:
  # fix Invalid character found in method name. HTTP method names must be token
  max-http-header-size: 10240000
  tomcat:
    max-http-header-size: 10240000
    max-http-form-post-size: 10240000
    uri-encoding: UTF-8
  servlet:
    context-path: /
  compression:
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/javascript
    min-response-size: 1024
    enabled: true

#fastjson:
#  parser:
#    autoTypeAccept: com.storlead.model.


